replicaCount: 1

image:
  repository: krishum77/messaging-api
  pullPolicy: Always
  tag: 'latest'

containerPort: 3003
imagePullSecrets: []
nameOverride: ''
fullnameOverride: 'messaging-api'

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3003

ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingres.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: 'writco.local'
      paths:
        - path: /api/messaging(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    memory: '512Mi'
    cpu: '750m'
  requests:
    memory: '300Mi'
    cpu: '300m'

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

nodeSelector: {}

tolerations: []

affinity: {}

database:
  enabled: false
  name: mysql-messaging
  storage: 1G
  storageClassName: standard
  user: cjhfjhfo=
  password: hfkjdhkuty49yet9ehkuhdg8rhdoh
  dbName: messaging
