apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: writco-def
spec:
  ports:
    - port: 3306
  selector:
    app: writco-database
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writco-database
  namespace: writco-def
spec:
  selector:
    matchLabels:
      app: writco-database
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: writco-database
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: db-user-username
                  name: db-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-user-password
                  name: db-secret
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-user-password
                  name: db-secret
          args: ["--default-authentication-plugin=mysql_native_password"]

          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/mysql
            - name: db-initdb
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
        - name: db-initdb
          configMap:
            name: db-init-mysql
